version: '2'
services:
  chatter_zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
  chatter_kafka:
    image: wurstmeister/kafka:0.10.1.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 0.0.0.0
      KAFKA_ZOOKEEPER_CONNECT: chatter_zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  chatter_cassandra:
    image: cassandra:3.9
    ports:
      - "9042:9042"